#pragma config(Motor,  port2,           BaneBot1,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           BaneBot2,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           Gatherer,      tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Belt,          tmotorNormal, openLoop)
#pragma config(Motor,  port6,           Pitch,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Barrier,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
BaneBot1 is banebot motor
BaneBot2 is banebot motor
Gatherer is vex motor
Belt is drill motor (ran by servo)
cannon pitch is pitch motor (ran by servo)
Barrier is vex servo
*/

task main()
{
  bIfiAutonomousMode=false;                      //JSV is joystick vertical
  while(1==1)
  {
    motor[port2]=vexRT[Ch2]/2;                     //banebot1 is left JSV at full power
    motor[port3]=vexRT[Ch3]/2;                     //banebot2 is right JSV at full power

    if (vexRT[Ch6]==-127) motor[port4]=-127;     //Gatherer is bottom right  botton at full power
    if (vexRT[Ch6]==0) motor[port4]=0;           //Gatherer at zero power

    if (vexRT[Ch6]==127) motor[port5]=60;        //Belt is top right button (servo engaged into run position) - servo at 60
    if (vexRT[Ch6]==0) motor[port5]=0;           //Belt (servo disengaged) - servo at 0

    if (vexRT[Ch5]==127) motor[port6]=100;       //Pitch is top left button(servo engaged into up position) - servo at 100
    if (vexRT[Ch5]==0) motor[port6]=0;           //Pitch (servo disengaged) - servo at 0
    if (vexRT[Ch5]==-127) motor[port6]=-100;     //Pitch is bottom left button(servo engaged into down position) - servo at -100

    if ((vexRT[Ch5]==127)&&(vexRT[Ch6]==127)) motor[port7]=75;
    if ((vexRT[Ch5]==-127)&&(vexRT[Ch6]==-127)) motor[port7]=-15;
	}                                              //Barrier is both top buttons (servo is in up position) - servo at 75
}                                                //Barrier is both bottom buttons (servo is in down position) - servo at -15
