#pragma config(Motor,  port2,           BaneBot1,      tmotorNormal, openLoop)
#pragma config(Motor,  port3,           BaneBot2,      tmotorNormal, openLoop)
#pragma config(Motor,  port4,           Gatherer,      tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Belt1,         tmotorNormal, openLoop)
#pragma config(Motor,  port6,           Belt2,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Launcher,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
BaneBot1 is banebot motor
BaneBot2 is banebot motor
Gatherer is vex motor
belts two vex motors
lancher is drill motor (ran by servo)
*/

task main()
{
  bIfiAutonomousMode=false;                      //JSV is joystick vertical
  while(1==1)                                    //JSH is joystick horizontal
  {
    motor[port2]=vexRT[Ch2]/2;                   //banebot1 is left JSV at half power
    motor[port3]=vexRT[Ch3]/2;                   //banebot2 is right JSV at half power

    if (vexRT[Ch6]==-127) motor[port4]=-127;     //Gatherer is bottom left  botton at full power
    if (vexRT[Ch6]==0) motor[port4]=0;           //Gatherer at zero power

    if (vexRT[Ch5]==127) motor[port5]=127;       //belt1 is bottom right  botton at full power
    if (vexRT[Ch5]==0) motor[port5]=0;           //belt1 at zero power

    if (vexRT[Ch5]==127) motor[port6]=-127;      //belt2 is bottom right  botton at full power
    if (vexRT[Ch5]==0) motor[port6]=0;           //belt2 at zero power

    if (vexRT[Ch6]==127) motor[port7]=127;       //launcher fire possition
    if (vexRT[Ch6]==0) motor[port7]=-127;        //launcher pulled back
	}
}
