#pragma config(Motor,  port2,           BaneBot1,      tmotorNormal, openLoop)
#pragma config(Motor,  port3,           BaneBot2,      tmotorNormal, openLoop)
#pragma config(Motor,  port4,           Gatherer,      tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Catapult,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           TrapDoor,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
BaneBot1 is banebot motor
BaneBot2 is banebot motor
Gatherer is vex motor
Catapult is drill motor (ran by servo)
TrapDoor is vex servo
*/

task main()
{
  bIfiAutonomousMode=false;                      //JSV is joystick vertical
  while(1==1)                                    //JSH is joystick horizontal
  {
    motor[port2]=vexRT[Ch2]/2;                   //banebot1 is left JSV at full power
    motor[port3]=vexRT[Ch3]/2;                   //banebot2 is right JSV at full power

    if (vexRT[Ch5]==-127) motor[port4]=-127;     //Gatherer is bottom right  botton at full power
    if (vexRT[Ch5]==0) motor[port4]=0;           //Gatherer at zero power

    if (vexRT[Ch6]==127) motor[port5]=100;       //Catapult is top left button(servo engaged into up position) - servo at 100
    if (vexRT[Ch6]==0) motor[port5]=0;           //Catapult (servo disengaged) - servo at 0
    if (vexRT[Ch6]==-127) motor[port5]=-100;     //Catapult is bottom left button(servo engaged into down position) - servo at -100

    if (vexRT[Ch5]==127) motor[port6]=vexRT[Ch1];//TrapDoor is top left button - servo at left JSH
	}
}
