#pragma config(Motor,  port2,           BaneBot1,      tmotorNormal, openLoop)
#pragma config(Motor,  port3,           BaneBot2,      tmotorNormal, openLoop)
#pragma config(Motor,  port4,           Gatherer,      tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Belt1,         tmotorNormal, openLoop)
#pragma config(Motor,  port6,           Belt2,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Launcher,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
BaneBot1 is banebot motor
BaneBot2 is banebot motor
Gatherer is vex motor
belts two vex motors
lancher is drill motor (ran by servo)
*/

task main()
{
  bIfiAutonomousMode=false;             //JSV is joystick vertical
  while(vexRT[Ch6==127)                 //JSH is joystick horizontal
  {
    motor[port2]=-100;                  //banebot1 at full power
    motor[port3]=-100;                  //banebot2 at full power
    wait1Msec(2500);                    //run for 2.5 seconds

    motor[port4]=127;                   //gather at full power
    motor[port5]=127;                   //belt1 at full power
    motor[port6]=127;                   //Belt2 at full power
    wait1Msec(4500);                    //run for 4.5seconds

    motor[port2]=127;                   //banebot1 at full power
    motor[port3]=127;                   //banebot2 at full power
    motor[port7]=127;                   //launcher at run position
    wait1Msec(5500);                    //run for 5.5 seconds

    motor[port7]=127;                   //launcher at run position
    motor[port5]=127;                   //belt1 at full power
    motor[port6]=127;                   //Belt2 at full power
    wait1Msec(5500);                    //run for 5.5 seconds
